cmd_/media/sf_Labs/Lab4/chardev/implementation.o := gcc -Wp,-MD,/media/sf_Labs/Lab4/chardev/.implementation.o.d  -nostdinc -isystem /usr/lib/gcc/x86_64-linux-gnu/4.9/include  -I./arch/x86/include -Iarch/x86/include/generated  -Iinclude -I./arch/x86/include/uapi -Iarch/x86/include/generated/uapi -I./include/uapi -Iinclude/generated/uapi -include ./include/linux/kconfig.h -Iubuntu/include  -D__KERNEL__ -Wall -Wundef -Wstrict-prototypes -Wno-trigraphs -fno-strict-aliasing -fno-common -Werror-implicit-function-declaration -Wno-format-security -m64 -mno-mmx -mno-sse -mno-80387 -mno-fp-ret-in-387 -mpreferred-stack-boundary=3 -mtune=generic -mno-red-zone -mcmodel=kernel -funit-at-a-time -maccumulate-outgoing-args -DCONFIG_X86_X32_ABI -DCONFIG_AS_CFI=1 -DCONFIG_AS_CFI_SIGNAL_FRAME=1 -DCONFIG_AS_CFI_SECTIONS=1 -DCONFIG_AS_FXSAVEQ=1 -DCONFIG_AS_CRC32=1 -DCONFIG_AS_AVX=1 -DCONFIG_AS_AVX2=1 -pipe -Wno-sign-compare -fno-asynchronous-unwind-tables -mno-sse -mno-mmx -mno-sse2 -mno-3dnow -mno-avx -fno-delete-null-pointer-checks -O2 -Wframe-larger-than=1024 -fstack-protector -Wno-unused-but-set-variable -fno-omit-frame-pointer -fno-optimize-sibling-calls -fno-var-tracking-assignments -pg -mfentry -DCC_USING_FENTRY -Wdeclaration-after-statement -Wno-pointer-sign -fno-strict-overflow -fconserve-stack -Werror=implicit-int -Werror=strict-prototypes -Werror=date-time -DCC_HAVE_ASM_GOTO  -DMODULE  -D"KBUILD_STR(s)=\#s" -D"KBUILD_BASENAME=KBUILD_STR(implementation)"  -D"KBUILD_MODNAME=KBUILD_STR(mychardrv)" -c -o /media/sf_Labs/Lab4/chardev/.tmp_implementation.o /media/sf_Labs/Lab4/chardev/implementation.c

source_/media/sf_Labs/Lab4/chardev/implementation.o := /media/sf_Labs/Lab4/chardev/implementation.c

deps_/media/sf_Labs/Lab4/chardev/implementation.o := \

/media/sf_Labs/Lab4/chardev/implementation.o: $(deps_/media/sf_Labs/Lab4/chardev/implementation.o)

$(deps_/media/sf_Labs/Lab4/chardev/implementation.o):
