condvar-exercise: condvar-exercise.c
	gcc -O -pthread -o condvar-exercise condvar-exercise.c

condvar: condvar.c
	gcc -O -pthread -o condvar condvar.c

condvar-serial: condvar-serial.c
	gcc -O -pthread -o condvar-serial condvar-serial.c
